title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true

permalink: /:title/
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

logo: /assets/img/photo.jpg

markdown: kramdown
kramdown:
  parse_block_html: true

plugins:
 - jekyll-feed
